<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>74224041-a4dc-4563-b850-719a42cabdc3</elementGuidId>
    <imagePath></imagePath>
    <name>div_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/nav[1]/ul[2]/li[2]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="user-nav"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>