<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>dbe7247a-09d1-4d74-8f71-85e6156912ab</elementGuidId>
    <imagePath></imagePath>
    <name>h6_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/nav[1]/ul[2]/li[2]/div[1]/div[2]/h6[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="user-nav-sub-link\ margin-0\ d-flex"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>