<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>54d60df2-3d86-44ef-bd57-918b5cb7a817</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_home</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/nav[1]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li:nth-child(1) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Home')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Home</value>
        <webElementGuid>ba3f05fe-e4d0-410c-ab2b-93dee54dbf6a</webElementGuid>
    </webElementProperties>
</WebElementEntity>