<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>74e0f179-e452-4b0c-bf35-dd6fd4cc410d</elementGuidId>
    <imagePath></imagePath>
    <name>button_update_profile</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/div[2]/div[5]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="button\ w-100-mobile"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Update Profile')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Update Profile</value>
        <webElementGuid>ccec43a9-ebcc-4338-99f6-c28bdb13d7b0</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>ccec43a9-ebcc-4338-99f6-c28bdb13d7b0</webElementGuid>
    </webElementProperties>
</WebElementEntity>