<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b26d38cb-37c4-4f29-aeef-9521effdc9bf</elementGuidId>
    <imagePath></imagePath>
    <name>input_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/div[2]/div[4]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="form-control\ input-form\ d-block"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'tel')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>tel</value>
        <webElementGuid>bfc0c13d-c4a9-4424-a0c8-799914422473</webElementGuid>
    </webElementProperties>
</WebElementEntity>