<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>004a8d03-aa32-4bba-a8b7-1c70f551beb8</elementGuidId>
    <imagePath></imagePath>
    <name>input_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/div[2]/div[4]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="form-control\ input-form\ d-block"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'tel')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>tel</value>
        <webElementGuid>8371efd8-76e8-48d1-a7ba-d34a7a6add44</webElementGuid>
    </webElementProperties>
</WebElementEntity>