<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>42b4be60-60eb-43f7-9488-cb6d84af98b9</elementGuidId>
    <imagePath></imagePath>
    <name>li_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/div[1]/ul[1]/li[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="user-tab-item\ "]:nth-child(2)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>