<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>103825ac-b853-413a-85c8-eca8ebdd7dde</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_see_all</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/div[3]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="display"]:nth-child(3) a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'See All')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>See All</value>
        <webElementGuid>8371efd8-76e8-48d1-a7ba-d34a7a6add44</webElementGuid>
    </webElementProperties>
</WebElementEntity>