<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ae5c9cb4-6743-47d4-8fe3-2fa71557630b</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_see_all</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/div[3]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="display"]:nth-child(3) a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'See All')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>See All</value>
        <webElementGuid>e3d1eaec-49ba-4591-bb37-100d5047447d</webElementGuid>
    </webElementProperties>
</WebElementEntity>