<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3233e3c9-6eba-457b-92ae-aa09db834003</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_recommended</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/nav[1]/ul[1]/li[4]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li:nth-child(4) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Recommended')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Recommended</value>
        <webElementGuid>ccec43a9-ebcc-4338-99f6-c28bdb13d7b0</webElementGuid>
    </webElementProperties>
</WebElementEntity>